development:
  adapter: postgresql
  encoding: unicode
  database: lineup_manager_development
  pool: 5
  username: hoitomt
  password: badger

test:
  adapter: postgresql
  encoding: unicode
  database: lineup_manager_test
  pool: 5
  username: hoitomt
  password: badger